import { useEffect, useMemo, useRef, useState } from 'react'
import * as XLSX from 'xlsx'
import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, Clock3, Expand, RotateCw, Search, Shuffle, Sparkles, Volume2, X } from 'lucide-react'
import './App.css'
import './cue.css'

type VocabRow = Record<string, string | number | undefined> & { level: string; day: string; sourceRow: number }
type Workbook = { level: string; sheets: Record<string, VocabRow[]> }
type Tab = 'practice' | 'search' | 'test' | 'visuals'

const WORKBOOKS = [['A1', 'A1_vocab.xlsx'], ['A2', 'A2_vocab.xlsx'], ['B1', 'B1_vocab.xlsx'], ['B2', 'B2_vocab.xlsx'], ['Movie', 'Movie_vocab.xlsx'], ['OFFICIAL_GERMAN_A1_List', 'OFFICIAL_GERMAN_A1_List_vocab.xlsx'], ['TOPICS_WISE', 'TOPICS_WISE_vocab.xlsx']] as const
const DAY_DETAILS: Record<string, [string, string]> = { 'Day 1': ['Essential nouns I', 'Family, nature, weather and stationery'], 'Day 2': ['Social and greetings', 'Greetings, farewells and feelings'], 'Day 3': ['Essential nouns II', 'Home, people and transport'], 'Day 4': ['Directions and seasons', 'Places, weather and time'], 'Day 5': ['Verbs and time phrases', 'Essential actions and daily language'] }
const slides = Array.from({ length: 60 }, (_, i) => `/slides/slide-${String(i + 1).padStart(2, '0')}.webp`)
const clean = (value: unknown) => { const text = String(value ?? '').trim(); return text === 'nan' || text === 'undefined' ? '' : text }
const shuffled = <T,>(items: T[]) => [...items].sort(() => Math.random() - .5)
const genderLabel = (gender: string) => ({ masculine: 'der', feminine: 'die', neuter: 'das', phrase: 'Phrase', verb: 'Verb', pronoun: 'Pronoun', time: 'Time' }[gender.toLowerCase()] || gender || 'Vocabulary')

function audioPath(row: VocabRow) { const word = clean(row.german_word).replaceAll(' ', '_').replaceAll('/', '_').replace(/[^a-zA-Z0-9_\-äöüÄÖÜß]/g, '').replace(/_{2,}/g, '_'); return `/audio-cache/${encodeURIComponent(row.level)}/${encodeURIComponent(row.day)}/pronounce/row_${row.sourceRow + 2}_${encodeURIComponent(word)}.mp3` }
function speak(text: string, row?: VocabRow) { const fallback = () => { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'de-DE'; utterance.rate = .82; window.speechSynthesis.speak(utterance) }; if (!row) return fallback(); const player = document.getElementById('deutschflash-audio') as HTMLAudioElement | null; if (!player) return fallback(); player.pause(); player.src = audioPath(row); player.currentTime = 0; player.onerror = fallback; player.play().catch(fallback) }
function optionList(row: VocabRow) { const answer = clean(row.meaning); const options = [1, 2, 3, 4].map((n) => clean(row[`option_${n}`])).filter(Boolean); if (!options.includes(answer)) options[0] = answer; return shuffled([...new Set(options)]) }

export default function App() {
  const [workbooks, setWorkbooks] = useState<Workbook[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [tab, setTab] = useState<Tab>('practice')
  useEffect(() => { let active = true; async function load() { try { const results = await Promise.all(WORKBOOKS.map(async ([level, file]) => { const response = await fetch(`/data/${file}`); if (!response.ok) throw new Error(`Could not load ${file}`); const workbook = XLSX.read(await response.arrayBuffer(), { type: 'array' }); const sheets = Object.fromEntries(workbook.SheetNames.map((day) => [day, XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets[day], { defval: '' }).map((raw, sourceRow) => ({ ...raw, level, day, sourceRow }) as VocabRow).filter((row) => clean(row.german_word))])); return { level, sheets } })); if (active) setWorkbooks(results) } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : 'Could not load the vocabulary data.') } finally { if (active) setLoading(false) } } load(); return () => { active = false } }, [])
  if (loading) return <main className="app-shell loading"><div className="loader" /><p>Loading your vocabulary library...</p></main>
  if (error) return <main className="app-shell loading"><p>{error}</p></main>
  return <main className="app-shell"><audio id="deutschflash-audio" preload="auto" /><header className="site-header"><div className="brand"><span className="brand-mark">DF</span><div><strong>DeutschFlash</strong><small>Vocabulary studio</small></div></div><nav aria-label="Application sections">{(['practice', 'search', 'test', 'visuals'] as Tab[]).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</nav></header>{tab === 'practice' && <Practice workbooks={workbooks} />}{tab === 'search' && <WordSearch workbooks={workbooks} />}{tab === 'test' && <RandomTest workbooks={workbooks} />}{tab === 'visuals' && <Visuals />}</main>
}

function Practice({ workbooks }: { workbooks: Workbook[] }) {
  const available = workbooks.filter((w) => Object.values(w.sheets).some((rows) => rows.length)); const [level, setLevel] = useState(available[0]?.level ?? ''); const [deck, setDeck] = useState<VocabRow[] | null>(null); const [position, setPosition] = useState(0); const [chosen, setChosen] = useState<string | null>(null); const [showCue, setShowCue] = useState(false); const [score, setScore] = useState(0); const [streak, setStreak] = useState(0); const [bestStreak, setBestStreak] = useState(0); const workbook = available.find((entry) => entry.level === level)
  function start(rows: VocabRow[]) { setDeck(shuffled(rows)); setPosition(0); setChosen(null); setShowCue(false); setScore(0); setStreak(0); setBestStreak(0) }
  if (!deck) return <section className="content"><div className="eyebrow">German vocabulary</div><h1>Build recall, one word at a time.</h1><p className="lede">Choose a level and a sheet, then answer from memory. Your data stays in the browser.</p><label className="select-label">Level<select value={level} onChange={(e) => setLevel(e.target.value)}>{available.map((e) => <option key={e.level}>{e.level}</option>)}</select></label><div className="deck-list">{Object.entries(workbook?.sheets ?? {}).filter(([, rows]) => rows.length).map(([day, rows]) => { const [title, description] = DAY_DETAILS[day] ?? [day, 'Vocabulary collection']; return <article className="deck-row" key={day}><div><span>{day}</span><h2>{title}</h2><p>{description}</p></div><div className="deck-action"><b>{rows.length}</b><small>words</small><button className="icon-button" title={`Start ${day}`} onClick={() => start(rows)}><ArrowRight size={18} /></button></div></article> })}</div><button className="marathon" onClick={() => start(Object.values(workbook?.sheets ?? {}).flat())}><Shuffle size={17} /> Practice the full {level} library</button></section>
  if (position >= deck.length) return <section className="content summary"><Sparkles size={34} /><div className="eyebrow">Session complete</div><h1>Sehr gut.</h1><p>You completed {deck.length} cards with {deck.length ? Math.round(score / deck.length * 100) : 0}% accuracy.</p><div className="stat-grid"><Stat value={`${score}/${deck.length}`} label="Correct" /><Stat value={`${bestStreak}`} label="Best streak" /><Stat value={`${deck.length}`} label="Cards" /></div><button className="primary" onClick={() => start(deck)}>Practice again</button><button className="secondary" onClick={() => setDeck(null)}>Choose another deck</button></section>
  const row = deck[position]; const answer = clean(row.meaning); const options = optionList(row); const answered = chosen !== null
  function choose(option: string) { if (answered) return; setChosen(option); setShowCue(true); if (option === answer) { const next = streak + 1; setScore((v) => v + 1); setStreak(next); setBestStreak((v) => Math.max(v, next)) } else setStreak(0) }
  function next() { setPosition((v) => v + 1); setChosen(null); setShowCue(false) }
  return <section className="content quiz"><button className="back-button" onClick={() => setDeck(null)}><ArrowLeft size={16} /> Library</button><div className="quiz-meta"><span>{row.level} / {row.day}</span><span>{position + 1} of {deck.length}</span></div><div className="progress"><i style={{ width: `${position / deck.length * 100}%` }} /></div><div className="word-card"><div className="word-top"><span className={`gender ${clean(row.gender).toLowerCase()}`}>{genderLabel(clean(row.gender))}</span><span className="streak">Streak {streak}</span></div>{showCue ? <ImageCue key={`${row.level}-${row.day}-${row.sourceRow}`} row={row} /> : <button className="cue-button" onClick={() => setShowCue(true)}>Reveal visual cue</button>}<div className="word-line"><h1>{clean(row.german_word)}</h1><button className="speaker" title="Play pronunciation" onClick={() => speak(clean(row.german_word), row)}><Volume2 size={21} /></button></div><p className="phonetic">[{clean(row.pronunciation)}]</p>{clean(row.note) && <small className="note">{clean(row.note)}</small>}<div className="example"><p>{clean(row.example_sentence)}</p><button className="speaker small" title="Play example" onClick={() => speak(clean(row.example_sentence))}><Volume2 size={16} /></button></div></div><div className="options">{options.map((option) => <button key={option} onClick={() => choose(option)} className={answered ? option === answer ? 'correct' : option === chosen ? 'wrong' : 'muted' : ''}>{answered && option === answer && <Check size={17} />}{answered && option === chosen && option !== answer && <X size={17} />}{option}</button>)}</div>{answered && <div className={chosen === answer ? 'feedback correct-feedback' : 'feedback wrong-feedback'}><strong>{chosen === answer ? 'Richtig!' : 'Not quite.'}</strong><span>{clean(row.german_word)} means {answer}.</span></div>}{answered && <button className="primary next" onClick={next}>{position === deck.length - 1 ? 'See results' : 'Next card'} <ArrowRight size={17} /></button>}</section>
}

function ImageCue({ row }: { row: VocabRow }) {
  const [image, setImage] = useState(''); const [failed, setFailed] = useState(false); const query = clean(row.keyword) || clean(row.german_word)
  useEffect(() => { let active = true; fetch(`https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrnamespace=6&gsrlimit=1&prop=imageinfo&iiprop=url&iiurlwidth=640&format=json&origin=*`).then((response) => response.json()).then((data) => { const page = Object.values(data.query?.pages ?? {})[0] as { imageinfo?: { thumburl?: string; url?: string }[] } | undefined; const url = page?.imageinfo?.[0]?.thumburl ?? page?.imageinfo?.[0]?.url; if (active && url) setImage(url); else if (active) setFailed(true) }).catch(() => active && setFailed(true)); return () => { active = false } }, [query])
  return <div className="visual-cue">{image ? <img src={image} alt={query} onError={() => setFailed(true)} /> : <span>{clean(row.emoji) || '💡'}</span>}<small>{failed ? `${query} visual cue` : image ? query : 'Finding an image...'}</small></div>
}

function WordSearch({ workbooks }: { workbooks: Workbook[] }) { const [query, setQuery] = useState(''); const matches = useMemo(() => { const needle = query.trim().toLowerCase(); return !needle ? [] : workbooks.flatMap((w) => Object.values(w.sheets).flat()).filter((row) => `${clean(row.german_word)} ${clean(row.meaning)}`.toLowerCase().includes(needle)).sort((a, b) => clean(a.german_word).toLowerCase() === needle ? -1 : clean(b.german_word).toLowerCase() === needle ? 1 : 0).slice(0, 25) }, [query, workbooks]); return <section className="content"><div className="eyebrow">Vocabulary finder</div><h1>Search every word.</h1><div className="search-box"><Search size={19} /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Try Haus, mother, danke..." /></div>{query && <p className="result-count">{matches.length} result{matches.length === 1 ? '' : 's'}</p>}<div className="results">{matches.map((row) => <article className="result-card" key={`${row.level}-${row.day}-${row.sourceRow}`}><div><span className="location">{row.level} · {row.day}</span><h2>{clean(row.german_word)} <button className="speaker inline" title="Play pronunciation" onClick={() => speak(clean(row.german_word), row)}><Volume2 size={16} /></button></h2><p className="meaning">{clean(row.meaning)}</p><p>{clean(row.example_sentence)}</p></div><span className="result-emoji">{clean(row.emoji) || '💡'}</span></article>)}</div>{query && !matches.length && <div className="empty-state">No words matched that search.</div>}</section> }

function RandomTest({ workbooks }: { workbooks: Workbook[] }) {
  const available = workbooks.filter((w) => Object.values(w.sheets).some((rows) => rows.length)); const [level, setLevel] = useState(available[0]?.level ?? ''); const [mode, setMode] = useState<'level' | 'sheet'>('level'); const [sheet, setSheet] = useState(''); const [deck, setDeck] = useState<VocabRow[] | null>(null); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [answers, setAnswers] = useState<{ word: string; correct: string; selected: string; ok: boolean }[]>([]); const [seconds, setSeconds] = useState(0); const workbook = available.find((w) => w.level === level); const sheetNames = Object.entries(workbook?.sheets ?? {}).filter(([, rows]) => rows.length).map(([name]) => name)
  const activeSheet = sheetNames.includes(sheet) ? sheet : sheetNames[0] ?? ''
  useEffect(() => { if (!deck || selected !== null) return; const id = window.setInterval(() => setSeconds((v) => v - 1), 1000); return () => window.clearInterval(id) }, [deck, selected])
  function start() { const pool = mode === 'sheet' ? workbook?.sheets[activeSheet] ?? [] : Object.values(workbook?.sheets ?? {}).flat(); const valid = pool.filter((row) => clean(row.example_sentence)); const count = Math.min(mode === 'sheet' ? 10 : 25, valid.length); setDeck(shuffled(valid).slice(0, count)); setIndex(0); setSelected(null); setAnswers([]); setSeconds(mode === 'sheet' ? 50 : 125) }
  if (!deck) return <section className="content"><div className="eyebrow">Timed recall</div><h1>Random test.</h1><p className="lede">Read a sentence, spot its key word, then choose the meaning before time runs out.</p><label className="select-label">Level<select value={level} onChange={(e) => { const nextLevel = e.target.value; setLevel(nextLevel); const nextWorkbook = available.find((entry) => entry.level === nextLevel); setSheet(Object.keys(nextWorkbook?.sheets ?? {})[0] ?? '') }}>{available.map((e) => <option key={e.level}>{e.level}</option>)}</select></label><div className="mode-buttons"><button className={mode === 'level' ? 'selected' : ''} onClick={() => setMode('level')}>Level test<br /><small>25 questions · 125 seconds</small></button><button className={mode === 'sheet' ? 'selected' : ''} onClick={() => setMode('sheet')}>Sheet test<br /><small>10 questions · 50 seconds</small></button></div>{mode === 'sheet' && <label className="select-label">Sheet<select value={activeSheet} onChange={(e) => setSheet(e.target.value)}>{sheetNames.map((name) => <option key={name}>{name}</option>)}</select></label>}<button className="primary" onClick={start}>Start test <ArrowRight size={17} /></button></section>
  if (index >= deck.length || seconds <= 0) { const score = answers.filter((a) => a.ok).length; return <section className="content summary"><Sparkles size={34} /><div className="eyebrow">Test complete</div><h1>{seconds <= 0 ? 'Time is up.' : 'Nice work.'}</h1><div className="stat-grid"><Stat value={`${score}/${answers.length}`} label="Correct" /><Stat value={`${Math.max(0, seconds)}s`} label="Remaining" /><Stat value={`${answers.length}`} label="Answered" /></div><div className="review-list">{answers.filter((a) => !a.ok).map((a) => <p key={a.word}><X size={15} /> <b>{a.word}</b> means {a.correct}</p>)}</div><button className="primary" onClick={() => setDeck(null)}>New test</button></section> }
  const row = deck[index]; const answer = clean(row.meaning); const options = optionList(row); const time = `${Math.floor(seconds / 60)}:${String(Math.max(0, seconds % 60)).padStart(2, '0')}`; function choose(option: string) { if (selected) return; setSelected(option); setAnswers((items) => [...items, { word: clean(row.german_word), correct: answer, selected: option, ok: option === answer }]) }
  return <section className="content quiz test"><div className="timer"><Clock3 size={17} /> {time}</div><div className="quiz-meta"><span>{level} test</span><span>Question {index + 1} of {deck.length}</span></div><div className="progress"><i style={{ width: `${index / deck.length * 100}%` }} /></div><div className="test-card"><span className={`gender ${clean(row.gender).toLowerCase()}`}>{genderLabel(clean(row.gender))}</span><p className="sentence">{clean(row.example_sentence)}</p><button className="speaker small" title="Play sentence" onClick={() => speak(clean(row.example_sentence))}><Volume2 size={16} /></button><p className="prompt">What does <b>{clean(row.german_word)}</b> mean?</p></div><div className="options">{options.map((option) => <button key={option} onClick={() => choose(option)} className={selected ? option === answer ? 'correct' : option === selected ? 'wrong' : 'muted' : ''}>{option}</button>)}</div>{selected && <button className="primary next" onClick={() => { setIndex((v) => v + 1); setSelected(null) }}>{index === deck.length - 1 ? 'Finish test' : 'Next question'} <ArrowRight size={17} /></button>}</section>
}

function Visuals() { const [index, setIndex] = useState(0); const [rotate, setRotate] = useState(false); const viewer = useRef<HTMLDivElement>(null); const previous = () => setIndex((v) => Math.max(0, v - 1)); const next = () => setIndex((v) => Math.min(slides.length - 1, v + 1)); useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === 'ArrowLeft') previous(); if (event.key === 'ArrowRight') next() }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener) }, []); return <section className="content visual-content"><div className="eyebrow">Visual library</div><h1>Learn by visual context.</h1><div className="visual-toolbar"><label>Slide<select value={index} onChange={(e) => setIndex(Number(e.target.value))}>{slides.map((_, v) => <option key={v} value={v}>Slide {v + 1} of {slides.length}</option>)}</select></label><button className="icon-button" title="Rotate slide" onClick={() => setRotate((v) => !v)}><RotateCw size={17} /></button><button className="icon-button" title="Fullscreen" onClick={() => viewer.current?.requestFullscreen()}><Expand size={17} /></button></div><div className="slide-viewer" ref={viewer}><button className="slide-arrow left" title="Previous slide" onClick={previous} disabled={!index}><ChevronLeft /></button><img src={slides[index]} alt={`German lesson slide ${index + 1}`} className={rotate ? 'rotated' : ''} /><button className="slide-arrow right" title="Next slide" onClick={next} disabled={index === slides.length - 1}><ChevronRight /></button></div><div className="slide-dots"><span>{index + 1} / {slides.length}</span><input type="range" min="0" max={slides.length - 1} value={index} onChange={(e) => setIndex(Number(e.target.value))} /></div></section> }
function Stat({ value, label }: { value: string; label: string }) { return <div className="stat"><b>{value}</b><span>{label}</span></div> }
