export type CoreVocabularyEntry = {
  german: string
  english: string
  type: string
  category: string
}

const entries = (category: string, type: string, values: string[][]): CoreVocabularyEntry[] => values.map(([german, english]) => ({ german, english, type, category }))

export const CORE_80_20: CoreVocabularyEntry[] = [
  ...entries('Pronouns', 'pronoun', [
    ['ich', 'I'], ['du', 'you (informal)'], ['Sie', 'you (formal)'], ['er', 'he / it'], ['sie', 'she / they'], ['es', 'it'], ['wir', 'we'], ['ihr', 'you all'], ['mich', 'me'], ['dich', 'you (acc.)'], ['ihn', 'him'], ['uns', 'us'], ['euch', 'you all (acc.)'], ['mir', 'to me'], ['dir', 'to you'], ['ihnen', 'to them'], ['mein', 'my'], ['dein', 'your'], ['sein', 'his / its'], ['unser', 'our'], ['dieser', 'this'], ['jeder', 'every / each'], ['welcher', 'which'], ['man', 'one / people'], ['jemand', 'someone'], ['niemand', 'no one'], ['etwas', 'something'], ['nichts', 'nothing'], ['alles', 'everything'],
  ]),
  ...entries('Question words', 'question', [
    ['wer', 'who'], ['was', 'what'], ['wann', 'when'], ['wo', 'where'], ['warum', 'why'], ['wie', 'how'], ['welche', 'which one'], ['wieviel', 'how much'], ['woher', 'from where'], ['wohin', 'to where'],
  ]),
  ...entries('Numbers', 'number', [
    ['eins', 'one'], ['zwei', 'two'], ['drei', 'three'], ['vier', 'four'], ['fünf', 'five'], ['sechs', 'six'], ['sieben', 'seven'], ['acht', 'eight'], ['neun', 'nine'], ['zehn', 'ten'], ['zwanzig', 'twenty'], ['hundert', 'hundred'], ['tausend', 'thousand'], ['erste', 'first'], ['letzte', 'last'], ['viele', 'many'],
  ]),
  ...entries('Verbs', 'verb', [
    ['sein', 'to be'], ['haben', 'to have'], ['werden', 'to become'], ['können', 'can / to be able to'], ['müssen', 'must / to have to'], ['wollen', 'to want'], ['sollen', 'should'], ['dürfen', 'to be allowed to'], ['mögen', 'to like'], ['möchten', 'would like'], ['gehen', 'to go'], ['kommen', 'to come'], ['machen', 'to make / do'], ['sagen', 'to say'], ['sehen', 'to see'], ['wissen', 'to know (fact)'], ['kennen', 'to know (person / place)'], ['geben', 'to give'], ['nehmen', 'to take'], ['finden', 'to find'], ['denken', 'to think'], ['glauben', 'to believe'], ['bleiben', 'to stay'], ['liegen', 'to lie / be located'], ['lassen', 'to let / leave'], ['stehen', 'to stand'], ['heißen', 'to be called'], ['spielen', 'to play'], ['arbeiten', 'to work'], ['essen', 'to eat'], ['trinken', 'to drink'], ['schlafen', 'to sleep'], ['leben', 'to live'], ['lieben', 'to love'], ['brauchen', 'to need'], ['fahren', 'to drive / go by vehicle'], ['fragen', 'to ask'], ['antworten', 'to answer'], ['hören', 'to hear / listen'], ['sprechen', 'to speak'], ['lesen', 'to read'], ['schreiben', 'to write'], ['kaufen', 'to buy'], ['verkaufen', 'to sell'], ['kosten', 'to cost'], ['bezahlen', 'to pay'], ['helfen', 'to help'], ['warten', 'to wait'], ['beginnen', 'to begin'], ['anfangen', 'to start'], ['aufhören', 'to stop / end'], ['öffnen', 'to open'], ['schließen', 'to close'], ['suchen', 'to look for'], ['verstehen', 'to understand'], ['erklären', 'to explain'], ['zeigen', 'to show'], ['bringen', 'to bring'], ['holen', 'to fetch / get'], ['schicken', 'to send'], ['anrufen', 'to phone'], ['fühlen', 'to feel'], ['lernen', 'to learn'], ['studieren', 'to study'], ['reisen', 'to travel'], ['fliegen', 'to fly'], ['laufen', 'to run / walk'], ['sitzen', 'to sit'], ['legen', 'to lay / put'], ['setzen', 'to set / place'], ['stellen', 'to place upright'], ['tragen', 'to carry / wear'], ['treffen', 'to meet'], ['besuchen', 'to visit'], ['vergessen', 'to forget'], ['entscheiden', 'to decide'], ['versuchen', 'to try'], ['benutzen', 'to use'], ['ändern', 'to change'], ['verbessern', 'to improve'], ['üben', 'to practice'], ['planen', 'to plan'], ['kochen', 'to cook'], ['putzen', 'to clean'], ['waschen', 'to wash'], ['passieren', 'to happen'], ['bedeuten', 'to mean'], ['gehören', 'to belong'], ['gefallen', 'to please / like'], ['interessieren', 'to interest'], ['zahlen', 'to pay money'], ['verdienen', 'to earn'], ['wohnen', 'to reside'], ['danken', 'to thank'], ['gewinnen', 'to win'], ['verlieren', 'to lose'],
  ]),
  ...entries('Nouns', 'noun', [
    ['Zeit', 'time'], ['Jahr', 'year'], ['Tag', 'day'], ['Woche', 'week'], ['Monat', 'month'], ['Stunde', 'hour'], ['Minute', 'minute'], ['Mensch', 'person / human'], ['Mann', 'man'], ['Frau', 'woman'], ['Kind', 'child'], ['Familie', 'family'], ['Freund', 'friend'], ['Kollege', 'colleague'], ['Nachbar', 'neighbor'], ['Leute', 'people'], ['Haus', 'house'], ['Wohnung', 'apartment'], ['Zimmer', 'room'], ['Küche', 'kitchen'], ['Bad', 'bathroom'], ['Tür', 'door'], ['Fenster', 'window'], ['Tisch', 'table'], ['Stuhl', 'chair'], ['Bett', 'bed'], ['Auto', 'car'], ['Bus', 'bus'], ['Zug', 'train'], ['Fahrrad', 'bicycle'], ['Straße', 'street'], ['Stadt', 'city'], ['Land', 'country'], ['Welt', 'world'], ['Wasser', 'water'], ['Essen', 'food'], ['Brot', 'bread'], ['Milch', 'milk'], ['Kaffee', 'coffee'], ['Tee', 'tea'], ['Gemüse', 'vegetables'], ['Obst', 'fruit'], ['Geld', 'money'], ['Arbeit', 'work'], ['Schule', 'school'], ['Buch', 'book'], ['Handy', 'cellphone'], ['Computer', 'computer'], ['Internet', 'internet'], ['Sprache', 'language'], ['Wort', 'word'], ['Satz', 'sentence'], ['Frage', 'question'], ['Antwort', 'answer'], ['Problem', 'problem'], ['Lösung', 'solution'], ['Idee', 'idea'], ['Grund', 'reason'], ['Beispiel', 'example'], ['Teil', 'part'], ['Ende', 'end'], ['Anfang', 'beginning'], ['Seite', 'side / page'], ['Platz', 'place / square'], ['Weg', 'way / path'], ['Richtung', 'direction'], ['Wetter', 'weather'], ['Sonne', 'sun'], ['Regen', 'rain'], ['Schnee', 'snow'], ['Wind', 'wind'], ['Tier', 'animal'], ['Hund', 'dog'], ['Katze', 'cat'], ['Körper', 'body'], ['Kopf', 'head'], ['Hand', 'hand'], ['Fuß', 'foot'], ['Auge', 'eye'], ['Herz', 'heart'], ['Leben', 'life'], ['Liebe', 'love'], ['Glück', 'luck / happiness'], ['Angst', 'fear'], ['Gefühl', 'feeling'], ['Gedanke', 'thought'], ['Erfahrung', 'experience'], ['Fehler', 'mistake'], ['Hilfe', 'help'], ['Musik', 'music'], ['Film', 'movie'], ['Spiel', 'game'], ['Farbe', 'color'], ['Licht', 'light'], ['Nacht', 'night'], ['Morgen', 'morning'], ['Abend', 'evening'], ['Wochenende', 'weekend'], ['Geburtstag', 'birthday'], ['Geschenk', 'gift'], ['Reise', 'trip'], ['Urlaub', 'vacation'], ['Ziel', 'goal / destination'], ['Plan', 'plan'], ['Termin', 'appointment'], ['Nachricht', 'message / news'], ['Telefon', 'telephone'], ['Adresse', 'address'], ['Nummer', 'number'], ['Preis', 'price'], ['Rechnung', 'bill / invoice'], ['Bank', 'bank'], ['Geschäft', 'shop / business'], ['Supermarkt', 'supermarket'], ['Restaurant', 'restaurant'], ['Hotel', 'hotel'], ['Arzt', 'doctor'], ['Polizei', 'police'], ['Firma', 'company'], ['Kunde', 'customer'], ['Sache', 'thing / matter'], ['Name', 'name'],
  ]),
  ...entries('Adjectives', 'adjective', [
    ['gut', 'good'], ['schlecht', 'bad'], ['groß', 'big'], ['klein', 'small'], ['neu', 'new'], ['alt', 'old'], ['jung', 'young'], ['schön', 'beautiful'], ['hässlich', 'ugly'], ['lang', 'long'], ['kurz', 'short'], ['hoch', 'high'], ['niedrig', 'low'], ['schwer', 'heavy / difficult'], ['leicht', 'light / easy'], ['stark', 'strong'], ['schwach', 'weak'], ['schnell', 'fast'], ['langsam', 'slow'], ['warm', 'warm'], ['kalt', 'cold'], ['heiß', 'hot'], ['hell', 'bright'], ['dunkel', 'dark'], ['laut', 'loud'], ['leise', 'quiet'], ['sauber', 'clean'], ['schmutzig', 'dirty'], ['voll', 'full'], ['leer', 'empty'], ['teuer', 'expensive'], ['billig', 'cheap'], ['reich', 'rich'], ['arm', 'poor'], ['glücklich', 'happy'], ['traurig', 'sad'], ['müde', 'tired'], ['krank', 'sick'], ['gesund', 'healthy'], ['hungrig', 'hungry'], ['durstig', 'thirsty'], ['wichtig', 'important'], ['richtig', 'correct'], ['falsch', 'wrong'], ['einfach', 'simple'], ['schwierig', 'difficult'], ['möglich', 'possible'], ['sicher', 'safe / certain'], ['gefährlich', 'dangerous'], ['frei', 'free'], ['offen', 'open'], ['geschlossen', 'closed'], ['nah', 'near'], ['fern', 'far'], ['fertig', 'finished / ready'], ['interessant', 'interesting'], ['langweilig', 'boring'], ['freundlich', 'friendly'], ['nett', 'nice'], ['ruhig', 'calm'], ['nervös', 'nervous'], ['weich', 'soft'], ['hart', 'hard'], ['süß', 'sweet / cute'], ['frisch', 'fresh'], ['modern', 'modern'], ['normal', 'normal'], ['besonders', 'special / especially'], ['gleich', 'same / equal'], ['anders', 'different'], ['ähnlich', 'similar'], ['viel', 'much / a lot'], ['wenig', 'little / few'], ['ganz', 'whole / quite'], ['halb', 'half'], ['genau', 'exact'], ['eigen', 'own'], ['fremd', 'foreign / strange'], ['bekannt', 'known'], ['notwendig', 'necessary'], ['bereit', 'ready'], ['höflich', 'polite'], ['ehrlich', 'honest'],
  ]),
  ...entries('Adverbs / Connectors', 'adverb / connector', [
    ['und', 'and'], ['oder', 'or'], ['aber', 'but'], ['denn', 'because / for'], ['weil', 'because'], ['dass', 'that'], ['wenn', 'if / when'], ['ob', 'whether'], ['als', 'when / than'], ['während', 'while / during'], ['bevor', 'before'], ['nachdem', 'after'], ['obwohl', 'although'], ['also', 'so / therefore'], ['deshalb', 'therefore'], ['trotzdem', 'nevertheless'], ['außerdem', 'besides'], ['sonst', 'otherwise'], ['dann', 'then'], ['danach', 'after that'], ['jetzt', 'now'], ['heute', 'today'], ['morgen', 'tomorrow'], ['gestern', 'yesterday'], ['immer', 'always'], ['nie', 'never'], ['manchmal', 'sometimes'], ['oft', 'often'], ['selten', 'rarely'], ['schon', 'already'], ['noch', 'still / yet'], ['wieder', 'again'], ['hier', 'here'], ['dort', 'there'], ['überall', 'everywhere'], ['sehr', 'very'], ['zu', 'too'], ['fast', 'almost'], ['genug', 'enough'], ['mehr', 'more'], ['weniger', 'less'], ['nur', 'only'], ['auch', 'also'], ['sogar', 'even'], ['vielleicht', 'maybe'], ['wirklich', 'really'], ['natürlich', 'of course'], ['leider', 'unfortunately'], ['gern', 'gladly'], ['zusammen', 'together'], ['allein', 'alone'], ['ja', 'yes'], ['nein', 'no'],
  ]),
  ...entries('Prepositions', 'preposition', [
    ['in', 'in'], ['an', 'at / on'], ['auf', 'on / upon'], ['unter', 'under'], ['über', 'over / about'], ['vor', 'before / in front of'], ['hinter', 'behind'], ['neben', 'next to'], ['zwischen', 'between'], ['mit', 'with'], ['ohne', 'without'], ['für', 'for'], ['gegen', 'against'], ['um', 'around / at time'], ['durch', 'through'], ['bei', 'at / near'], ['nach', 'after / to'], ['von', 'from / of'], ['aus', 'out of / from'], ['seit', 'since'], ['wegen', 'because of'], ['trotz', 'despite'], ['bis', 'until'], ['außer', 'except'],
  ]),
]
